server:
  port: 11001
spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql:106.15.188.160:3306/xiaomo?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    data-username: xiaomo
    data-password: xiaomo
